In [3]:
#Import libraries
import pandas as pd
import sqlite3

In [5]:
#Connect to im db
conn = sqlite3.connect('DATA/im.db')
pd.read_sql("""
SELECT * FROM sqlite_master
WHERE TYPE = 'table';
""", conn)

,type,name,tbl_name,rootpage,sql
0,table,movie_basics,movie_basics,2,"CREATE TABLE ""movie_basics"" (\n""movie_id"" TEXT..."
1,table,directors,directors,3,"CREATE TABLE ""directors"" (\n""movie_id"" TEXT,\n..."
2,table,known_for,known_for,4,"CREATE TABLE ""known_for"" (\n""person_id"" TEXT,\..."
3,table,movie_akas,movie_akas,5,"CREATE TABLE ""movie_akas"" (\n""movie_id"" TEXT,\..."
4,table,movie_ratings,movie_ratings,6,"CREATE TABLE ""movie_ratings"" (\n""movie_id"" TEX..."
5,table,persons,persons,7,"CREATE TABLE ""persons"" (\n""person_id"" TEXT,\n ..."
6,table,principals,principals,8,"CREATE TABLE ""principals"" (\n""movie_id"" TEXT,\..."
7,table,writers,writers,9,"CREATE TABLE ""writers"" (\n""movie_id"" TEXT,\n ..."

In [7]:
#Looking at the ratings table
ratings = pd.read_sql("""
SELECT * FROM movie_ratings;
""", conn)
ratings.head(10)

     movie_id  averagerating  numvotes
0  tt10356526            8.3        31
1  tt10384606            8.9       559
2   tt1042974            6.4        20
3   tt1043726            4.2     50352
4   tt1060240            6.5        21
5   tt1069246            6.2       326
6   tt1094666            7.0      1613
7   tt1130982            6.4       571
8   tt1156528            7.2       265
9   tt1161457            4.2       148

In [19]:
#Look at the movie basics info
basics = pd.read_sql("""
SELECT * FROM movie_basics;
""", conn)
basics.head()

,movie_id,primary_title,original_title,start_year,runtime_minutes,genres
0,tt0063540,Sunghursh,Sunghursh,2013,175.0,"Action,Crime,Drama"
1,tt0066787,One Day Before the Rainy Season,Ashad Ka Ek Din,2019,114.0,"Biography,Drama"
2,tt0069049,The Other Side of the Wind,The Other Side of the Wind,2018,122.0,Drama
3,tt0069204,Sabse Bada Sukh,Sabse Bada Sukh,2018,NaN,"Comedy,Drama"
4,tt0100275,The Wandering Soap Opera,La Telenovela Errante,2017,80.0,"Comedy,Drama,Fantasy"

In [35]:
#Looking at the movies akas info
akas = pd.read_sql("""
SELECT * FROM movie_akas;
""", conn)
akas

,movie_id,ordering,title,region,language,types,attributes,is_original_title
0,tt0369610,10,Джурасик свят,BG,bg,None,None,0.0
1,tt0369610,11,Jurashikku warudo,JP,None,imdbDisplay,None,0.0
2,tt0369610,12,Jurassic World: O Mundo dos Dinossauros,BR,None,imdbDisplay,None,0.0
3,tt0369610,13,O Mundo dos Dinossauros,BR,None,None,short title,0.0
4,tt0369610,14,Jurassic World,FR,None,imdbDisplay,None,0.0
...,...,...,...,...,...,...,...,...
331698,tt9827784,2,Sayonara kuchibiru,None,None,original,None,1.0
331699,tt9827784,3,Farewell Song,XWW,en,imdbDisplay,None,0.0
331700,tt9880178,1,La atención,None,None,original,None,1.0
331701,tt9880178,2,La atención,ES,None,None,None,0.0
331702,tt9880178,3,The Attention,XWW,en,imdbDisplay,None,0.0

In [39]:
#Joining all the data in movie_basics and movie_ratings table

df = pd.read_sql("""
SELECT
    movie_basics.movie_id,
    movie_basics.primary_title,
    movie_basics.start_year,
    movie_basics.genres,
    movie_ratings.averagerating,
    movie_ratings.numvotes
FROM movie_basics
JOIN movie_ratings USING(movie_id);
""", conn)
df

,movie_id,primary_title,start_year,genres,averagerating,numvotes
0,tt0063540,Sunghursh,2013,"Action,Crime,Drama",7.0,77
1,tt0066787,One Day Before the Rainy Season,2019,"Biography,Drama",7.2,43
2,tt0069049,The Other Side of the Wind,2018,Drama,6.9,4517
3,tt0069204,Sabse Bada Sukh,2018,"Comedy,Drama",6.1,13
4,tt0100275,The Wandering Soap Opera,2017,"Comedy,Drama,Fantasy",6.5,119
...,...,...,...,...,...,...
73851,tt9913084,Diabolik sono io,2019,Documentary,6.2,6
73852,tt9914286,Sokagin Çocuklari,2019,"Drama,Family",8.7,136
73853,tt9914642,Albatross,2017,Documentary,8.5,8
73854,tt9914942,La vida sense la Sara Amat,2019,None,6.6,5
73855,tt9916160,Drømmeland,2019,Documentary,6.5,11

In [45]:
# After storin the data in our df we can now cleen it and check for missing and null null values
df.isna().sum()

movie_id           0
primary_title      0
start_year         0
genres           804
averagerating      0
numvotes           0
dtype: int64

In [47]:
#Scince the only null values are in genres and they are less than 1 percent we can drop all the columns with genres missing
df = df.dropna()
df.isna().sum()

movie_id         0
primary_title    0
start_year       0
genres           0
averagerating    0
numvotes         0
dtype: int64

In [49]:
#Now we can post the dtat to a csv file so that we can merge with the 'bom.movie_gross csv file'.
df.to_csv('DATA/im.csv', index=False)

In [ ]:
#